SELECT
  TABLE_1.E_CUST_CEKE_LOGIN_ID                AS NIK
, CAST(TABLE_MASTER.CIF  AS DECIMAL(10,0))          AS CIF
, COALESCE (TABLE_3.CHNL_TYP,0)                     AS CHNL_TYPE_CD
, COALESCE(TABLE_1.E_CUST_PROFILE_ID,0)              AS PROFILE_CD
, TABLE_1.E_CUST_CHNL_ACT_STA_CDE AS NIK_ACT_STA_CD
, TABLE_3.CHANNEL_STA_CDE AS CHNL_STA_CD
, TABLE_1.E_CUST_AGREEMENT_VER_NO AS UBE_VER_NO
, CAST(CAST(TABLE_3.LAST_LOGIN_CHNL_DTE AS VARCHAR(19)) AS TIMESTAMP(0)) AS MAX_SUCCESS_LOG_DT
, CASE
WHEN TABLE_1.E_CUST_PROFILE_ID = 0   THEN 'DEFAULT'
WHEN TABLE_1.E_CUST_PROFILE_ID = 1   THEN 'Pasywny'
WHEN TABLE_1.E_CUST_PROFILE_ID = 2   THEN 'Predefiniowany'
WHEN TABLE_1.E_CUST_PROFILE_ID = 3   THEN 'TOKEN/SMSKOD'
WHEN TABLE_1.E_CUST_PROFILE_ID = 4   THEN 'Pasywny'
WHEN TABLE_1.E_CUST_PROFILE_ID = 5   THEN 'Predefiniowany'
WHEN TABLE_1.E_CUST_PROFILE_ID = 6   THEN 'Smskod'
WHEN TABLE_1.E_CUST_PROFILE_ID = 8   THEN 'Moja Firma +'
WHEN TABLE_1.E_CUST_PROFILE_ID = 9   THEN 'Moja Firma + uzytkownik'
WHEN TABLE_1.E_CUST_PROFILE_ID = 10   THEN 'Minibank24'
WHEN TABLE_1.E_CUST_PROFILE_ID = 11   THEN 'Minibank24 (P)'
WHEN TABLE_1.E_CUST_PROFILE_ID = 12   THEN 'Minibank24 +'
WHEN TABLE_1.E_CUST_PROFILE_ID = 13   THEN 'Minibank24 + BZWBK24(P)'
WHEN TABLE_1.E_CUST_PROFILE_ID = 14   THEN 'Moja Firma Ekstra'
WHEN TABLE_1.E_CUST_PROFILE_ID = 15   THEN 'Agent'
WHEN TABLE_1.E_CUST_PROFILE_ID = 16   THEN 'Agent uzytkownik'
WHEN TABLE_1.E_CUST_PROFILE_ID = 17   THEN 'B2B'
WHEN TABLE_1.E_CUST_PROFILE_ID = 18   THEN 'B2B uzytkownik'
WHEN TABLE_1.E_CUST_PROFILE_ID = 19   THEN 'ibiznes24'
WHEN TABLE_1.E_CUST_PROFILE_ID = 20   THEN 'ibiznes24 uzytkownik'
WHEN TABLE_1.E_CUST_PROFILE_ID = 24   THEN 'Mini Firma'
WHEN TABLE_1.E_CUST_PROFILE_ID = 25   THEN 'BZWBK24 MINI FIRMA'
WHEN TABLE_1.E_CUST_PROFILE_ID = 26   THEN 'ibiznes24 SME MB24'
WHEN TABLE_1.E_CUST_PROFILE_ID = 27   THEN 'ibiznes24 SME Moja Firma +'
  END                           AS PROFILE_DESC
, CASE
    WHEN TABLE_1.E_CUST_CHNL_ACT_STA_CDE = 0 THEN 'Aktywny'
    WHEN TABLE_1.E_CUST_CHNL_ACT_STA_CDE = 4 THEN 'Prejestrowany'
    WHEN TABLE_1.E_CUST_CHNL_ACT_STA_CDE = 5 THEN 'Zablokowany (klient)'
    WHEN TABLE_1.E_CUST_CHNL_ACT_STA_CDE = 6 THEN 'Zablokowany (Bank)'
    WHEN TABLE_1.E_CUST_CHNL_ACT_STA_CDE = 9 THEN 'Usuniety'
   END                           AS NIK_ACT_STA_DESC
,COALESCE( CAST(TABLE_6.SRCE_CUST_NO AS DECIMAL(10,0)) , 0 )         AS RELATED_CIF
,COALESCE( TABLE_4.E_CUST_JOINT_OWN_CEKE_LOGIN_ID,0)                  AS RELATED_NIK
,COALESCE( TABLE_6.E_CUST_PROFILE_ID,0)               AS RELATED_PROFILE_CD
, CASE
    WHEN TABLE_6.E_CUST_PROFILE_ID = 9   THEN 'Moja Firma +'
    WHEN TABLE_6.E_CUST_PROFILE_ID = 16  THEN 'Agent'
    WHEN TABLE_6.E_CUST_PROFILE_ID = 18  THEN 'B2B'
    WHEN TABLE_6.E_CUST_PROFILE_ID = 20  THEN 'ibiznes24'
    WHEN TABLE_6.E_CUST_PROFILE_ID = 25  THEN 'Mini Firma'
  END                           AS RELATED_PROFILE_DESC
, COALESCE(TABLE_5.CHNL_TYP,0)                     AS RELATED_CHNL_TYPE_CD

,COALESCE( TABLE_2.ALERT_PKG_TYP, 0)                   AS PACKAGE_TYPE_CD
, CASE
 WHEN TABLE_2.ALERT_PKG_TYP IN (3,8) THEN 'Moje Pieniadze'
WHEN TABLE_2.ALERT_PKG_TYP IN (5) THEN 'Bezplatny Pakiet Informacyjny'
WHEN TABLE_2.ALERT_PKG_TYP IN (6) THEN 'Pakiet Marketingowy'
WHEN TABLE_2.ALERT_PKG_TYP IN (9) THEN 'Moja Karta Sluzbowa'
WHEN TABLE_2.ALERT_PKG_TYP IN (9) THEN 'Moja Karta Sluzbowa'
WHEN TABLE_2.ALERT_PKG_TYP IN (11,13) THEN 'Maxi'
WHEN TABLE_2.ALERT_PKG_TYP IN (12) THEN 'Mini'
WHEN TABLE_2.ALERT_PKG_TYP IN (101) THEN 'Zewnetrzny'
  END                          AS PACKAGE_TYPE_DESC
, COALESCE(TABLE_2.E_SERVICE_STATUS_CDE, 0) AS PACKAGE_STA_CD
,CASE WHEN TABLE_7.SECNDRY_CUST_TO_CUST_REL_CDE IS NULL OR TABLE_7.SECNDRY_CUST_TO_CUST_REL_CDE = ' '
THEN  'XXX' ELSE TABLE_7.SECNDRY_CUST_TO_CUST_REL_CDE END    AS  REL_TYP_CD

,CASE WHEN TABLE_2.ALERT_PKG_TYP = 12 AND TABLE_2.E_SERVICE_STATUS_CDE = 0 AND TABLE_2.E_SERVICE_END_DTE IS NULL THEN 1 ELSE 0 END AS ALERTY24_MINI_FLG

FROM  PUB_TERADATA_DB_MIS29.BASE_CUST_MAP TABLE_MASTER

LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUSTOMER_DETAIL TABLE_1 ON TABLE_1.WH_CUST_NO = TABLE_MASTER.WH_CUST_NO
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_SERVICE_DETAIL TABLE_2 ON TABLE_2.WH_CUST_NO = TABLE_1.WH_CUST_NO
AND TABLE_2.E_CUST_CEKE_LOGIN_ID = TABLE_1.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_CHNL_USAGE_DETAIL TABLE_3 ON TABLE_3.WH_CUST_NO = TABLE_1.WH_CUST_NO
AND TABLE_3.E_CUST_CEKE_LOGIN_ID = TABLE_1.E_CUST_CEKE_LOGIN_ID AND TABLE_3.CHANNEL_STA_CDE <> '9'
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_E_CUST_REL TABLE_4 ON TABLE_1.E_CUST_CEKE_LOGIN_ID = TABLE_4.E_CUST_CEKE_LOGIN_ID AND TABLE_4.END_DTE IS NULL
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_CHNL_USAGE_DETAIL TABLE_5 ON TABLE_4.E_CUST_JOINT_OWN_CEKE_LOGIN_ID = TABLE_5.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUSTOMER_DETAIL TABLE_6 ON TABLE_6.WH_CUST_NO = TABLE_5.WH_CUST_NO
AND TABLE_5.E_CUST_CEKE_LOGIN_ID = TABLE_6.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.CUSTOMER_CUSTOMER_REL_DAILY TABLE_7 ON  cast(TABLE_7.SRCE_CUST_NO as DECIMAL(10,0))  = TABLE_MASTER.CIF
AND TABLE_7.SECNDRY_SRCE_CUST_NO = TABLE_6.SRCE_CUST_NO
LEFT JOIN PUB_TERADATA_DB_VIEWS01.CHANNEL TABLE_8 ON TABLE_8.CHNL_TYP = TABLE_3.CHNL_TYP
LEFT JOIN PUB_TERADATA_DB_VIEWS01.CHANNEL TABLE_9 ON TABLE_9.CHNL_TYP = TABLE_5.CHNL_TYP
WHERE TABLE_1.E_CUST_CEKE_LOGIN_ID IS NOT NULL

GROUP BY
NIK,
CIF,
CHNL_TYPE_CD,

PROFILE_CD,
NIK_ACT_STA_CD,
CHNL_STA_CD,
UBE_VER_NO,
MAX_SUCCESS_LOG_DT,
PROFILE_DESC,
NIK_ACT_STA_DESC,
RELATED_CIF,
RELATED_NIK,
RELATED_PROFILE_CD,
RELATED_PROFILE_DESC,
RELATED_CHNL_TYPE_CD,

PACKAGE_TYPE_CD,
PACKAGE_TYPE_DESC,
PACKAGE_STA_CD,
REL_TYP_CD,
ALERTY24_MINI_FLG
;

SELECT
TABLE_MASTER.NIK as NIK
,cast(count(TABLE_1.LOGINID)/30 as decimal(4,0)) AS AVG_LOG_IN_B24INT_D_CNT

FROM CAR.CMT_CEKE_0 TABLE_MASTER

LEFT JOIN PUB_TERADATA_DB_MIS29.CEKE_LOGINSTATS as TABLE_1
ON TABLE_MASTER.NIK = TABLE_1.LOGINID
AND TABLE_1.TIME_M >= PROCESSING_DATE - 30
AND TABLE_1.RETURNEDSTATUS = 0
AND upper(TABLE_1.SERVICENAME) = 'ILOGONOPT'

GROUP BY
TABLE_MASTER.NIK
;

SELECT
TABLE_MASTER.NIK AS NIK
,TABLE_1.POSTED_DTE AS TR_DR_TRANSFER_B24INT_MAX_DT
,TABLE_MASTER.CIF AS CIF
, TABLE_MASTER.CHNL_TYPE_CD AS CHNL_TYPE_CD
, TABLE_MASTER.PROFILE_CD
, TABLE_MASTER.RELATED_CIF
, TABLE_MASTER.RELATED_NIK
, TABLE_MASTER.RELATED_PROFILE_CD
, TABLE_MASTER.RELATED_CHNL_TYPE_CD
, TABLE_MASTER.PACKAGE_TYPE_CD
, TABLE_MASTER.PACKAGE_STA_CD
, TABLE_MASTER.REL_TYP_CD
, parameter AS ARCH_DATE
FROM
(
SELECT DISTINCT
  TABLE_1.E_CUST_CEKE_LOGIN_ID                AS NIK
, CAST(TABLE_1.SRCE_CUST_NO  AS DECIMAL(10,0))          AS CIF
, COALESCE (TABLE_3.CHNL_TYP,0)                     AS CHNL_TYPE_CD
, COALESCE(TABLE_1.E_CUST_PROFILE_ID,0)              AS PROFILE_CD
,COALESCE( CAST(TABLE_6.SRCE_CUST_NO AS DECIMAL(10,0)) , 0 )         AS RELATED_CIF
,COALESCE( TABLE_4.E_CUST_JOINT_OWN_CEKE_LOGIN_ID,0)                  AS RELATED_NIK
,COALESCE( TABLE_6.E_CUST_PROFILE_ID,0)               AS RELATED_PROFILE_CD
, COALESCE(TABLE_5.CHNL_TYP,0)                     AS RELATED_CHNL_TYPE_CD
,COALESCE( TABLE_2.ALERT_PKG_TYP, 0)                   AS PACKAGE_TYPE_CD
, COALESCE(TABLE_2.E_SERVICE_STATUS_CDE, 0) AS PACKAGE_STA_CD
, COALESCE(TABLE_7.SECNDRY_CUST_TO_CUST_REL_CDE, '' )   AS  REL_TYP_CD


FROM
 PUB_TERADATA_DB_VIEWS08.E_CUSTOMER_DETAIL TABLE_1
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_SERVICE_DETAIL TABLE_2 ON TABLE_2.WH_CUST_NO = TABLE_1.WH_CUST_NO
AND TABLE_2.E_CUST_CEKE_LOGIN_ID = TABLE_1.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_CHNL_USAGE_DETAIL TABLE_3 ON TABLE_3.WH_CUST_NO = TABLE_1.WH_CUST_NO
AND TABLE_3.E_CUST_CEKE_LOGIN_ID = TABLE_1.E_CUST_CEKE_LOGIN_ID AND TABLE_3.CHANNEL_STA_CDE <> '9'
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_E_CUST_REL TABLE_4 ON TABLE_1.E_CUST_CEKE_LOGIN_ID = TABLE_4.E_CUST_CEKE_LOGIN_ID AND TABLE_4.END_DTE IS NULL
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUST_CHNL_USAGE_DETAIL TABLE_5 ON TABLE_4.E_CUST_JOINT_OWN_CEKE_LOGIN_ID = TABLE_5.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.E_CUSTOMER_DETAIL TABLE_6 ON TABLE_6.WH_CUST_NO = TABLE_5.WH_CUST_NO
AND TABLE_5.E_CUST_CEKE_LOGIN_ID = TABLE_6.E_CUST_CEKE_LOGIN_ID
LEFT JOIN PUB_TERADATA_DB_VIEWS08.CUSTOMER_CUSTOMER_REL_DAILY TABLE_7 ON TABLE_7.SRCE_CUST_NO = TABLE_1.SRCE_CUST_NO
AND TABLE_7.SECNDRY_SRCE_CUST_NO = TABLE_6.SRCE_CUST_NO
WHERE TABLE_1.E_CUST_CEKE_LOGIN_ID IS NOT NULL ) TABLE_MASTER

JOIN
(
SELECT
E_CUST_CEKE_LOGIN_ID
,MAX(POSTED_DTE) AS POSTED_DTE
FROM
PUB_TERADATA_DB_VIEWS01.TRANSACTION_E_CHNL_DETAIL
where
POSTED_DTE<=parameter

GROUP BY 1
)
TABLE_1
ON TABLE_MASTER.NIK = TABLE_1.E_CUST_CEKE_LOGIN_ID
;